# Generated by Django 2.0.1 on 2018-04-12 12:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('poopdeck', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cgr',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IDnumber', models.IntegerField()),
                ('Company', models.CharField(max_length=100)),
                ('DurationRange', models.CharField(max_length=30)),
                ('DutyDriver', models.CharField(max_length=30)),
                ('SergeantOfGuard', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='ConnectDay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CallID', models.IntegerField()),
                ('CalenderDate', models.DateField()),
                ('ServicesID', models.IntegerField()),
                ('Weather', models.CharField(max_length=50)),
                ('Uniform', models.CharField(max_length=20)),
                ('TAPS', models.IntegerField()),
                ('DescriptionOfDay', models.CharField(max_length=30)),
                ('CGREventID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poopdeck.Cgr')),
            ],
        ),
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IDnumber', models.IntegerField()),
                ('Description', models.CharField(max_length=100)),
                ('DurationRange', models.CharField(max_length=30)),
                ('ImportanceStatus', models.CharField(max_length=30)),
                ('Location', models.CharField(max_length=30)),
                ('CompletionStatus', models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Meals',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MealID', models.IntegerField()),
                ('TypeofMeal', models.CharField(max_length=20)),
                ('SpecialOccasion', models.CharField(max_length=30)),
                ('Location', models.CharField(max_length=30)),
                ('DurationRange', models.CharField(max_length=30)),
                ('AnnouncementsMade', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IDNumber', models.IntegerField()),
                ('Description', models.CharField(max_length=100)),
                ('DurationRange', models.CharField(max_length=30)),
                ('Location', models.CharField(max_length=30)),
                ('Status', models.CharField(max_length=30)),
            ],
        ),
        migrations.DeleteModel(
            name='Cadet',
        ),
        migrations.AddField(
            model_name='day',
            name='EventID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poopdeck.Events'),
        ),
        migrations.AddField(
            model_name='day',
            name='MealID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poopdeck.Meals'),
        ),
        migrations.AddField(
            model_name='connectday',
            name='CallID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poopdeck.Day'),
        ),
        migrations.AddField(
            model_name='connectday',
            name='IDnumber',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poopdeck.Services'),
        ),
    ]
