# Generated by Django 2.0.1 on 2018-04-30 13:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('poopdeck', '0002_auto_20180412_1247'),
    ]

    operations = [
        migrations.RenameField(
            model_name='connectday',
            old_name='CallID',
            new_name='Call',
        ),
        migrations.RenameField(
            model_name='day',
            old_name='EventID',
            new_name='Event',
        ),
        migrations.RemoveField(
            model_name='cgr',
            name='IDnumber',
        ),
        migrations.RemoveField(
            model_name='day',
            name='CGREventID',
        ),
        migrations.RemoveField(
            model_name='day',
            name='CallID',
        ),
        migrations.RemoveField(
            model_name='day',
            name='MealID',
        ),
        migrations.RemoveField(
            model_name='events',
            name='IDnumber',
        ),
        migrations.RemoveField(
            model_name='meals',
            name='MealID',
        ),
        migrations.RemoveField(
            model_name='services',
            name='IDNumber',
        ),
        migrations.AddField(
            model_name='cgr',
            name='Day',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='poopdeck.Day'),
        ),
        migrations.AddField(
            model_name='meals',
            name='Day',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='poopdeck.Day'),
        ),
        migrations.AlterField(
            model_name='day',
            name='CalenderDate',
            field=models.IntegerField(),
        ),
    ]
