# Generated by Django 2.0.1 on 2018-04-30 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poopdeck', '0003_auto_20180430_1339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='day',
            name='CalenderDate',
            field=models.DateField(),
        ),
    ]
