# Generated by Django 2.0.1 on 2018-05-03 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poopdeck', '0005_auto_20180502_1306'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='day',
            name='ServicesID',
        ),
    ]
