# Generated by Django 2.0.1 on 2018-05-03 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poopdeck', '0006_remove_day_servicesid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='day',
            name='CalenderDate',
            field=models.IntegerField(),
        ),
    ]
